/* MainframeMint — engine parity suite.
 * The GnuCOBOL binary is compiled and diffed against tests/goldens.txt in CI
 * (job `cobol-goldens`). goldens.txt itself is generated by an EXACT
 * decimal.Decimal oracle (scripts/gen_goldens.py). This suite closes the
 * chain: the shipped JS mirror must reproduce EVERY golden byte-for-byte,
 * so browser results === COBOL results. */
import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { runCase, rha, monthlyInt, compound, amort, saving } from "../js/mmcore.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const caseLines = readFileSync(path.join(here, "cases.txt"), "utf8").trim().split(/\r?\n/);
const goldenLines = readFileSync(path.join(here, "goldens.txt"), "utf8").trim().split(/\r?\n/);

const N = parseInt(caseLines[0], 10);

test("case file header matches golden count", () => {
  assert.equal(N, goldenLines.length);
  assert.ok(N >= 30, "expected at least 30 vectors");
});

for (let i = 0; i < N; i++) {
  const [pgm, m, c, r, d] = caseLines[i + 1].trim().split(/\s+/);
  const expected = goldenLines[i].trim();
  const label = `${pgm}(${m},${c},${r},${d})`;
  if (["MFCOMPD", "MFAMORT", "MFSAVING"].includes(pgm)) {
    test(`parity vs COBOL golden #${i + 1}: ${label}`, () => {
      const out = runCase(pgm, parseInt(m, 10), parseInt(c, 10), parseInt(r, 10), parseInt(d, 10));
      assert.equal(`${out.a} ${out.b} ${out.c} ${out.s}`, expected);
    });
  } else {
    test(`unknown program rejected #${i + 1}: ${label}`, () => {
      const out = runCase(pgm, 1, 2, 3, 4);
      assert.equal(out.s, -99);
    });
  }
}

/* ---------- rounding primitives ---------- */
test("rha: half away from zero", () => {
  assert.equal(rha(2.5), 3);
  assert.equal(rha(-2.5), -3);
  assert.equal(rha(3.5), 4);
  assert.equal(rha(0.5), 1);
  assert.equal(rha(-0.5), -1);
});

test("rha: banker-free plain halves never round toward zero", () => {
  for (const x of [0.5, 1.5, 2.5, 6.5, 7.5]) {
    assert.equal(rha(x), Math.round(Math.abs(x)) === Math.floor(x) + 1 ? Math.floor(x) + 1 : Math.round(x));
    assert.notEqual(rha(-x), 0);
  }
});

test("monthlyInt: nominal-annual bps -> monthly whole-cent posting", () => {
  assert.equal(monthlyInt(100000, 600), 500);   // R$1.000 @ 6% a.a. -> 0,5%/month
  assert.equal(monthlyInt(1200000, 1200), 12000); // R$12.000 @ 12% a.a. -> 1%/month
  assert.equal(monthlyInt(100000, 0), 0);
});

/* ---------- status-code contract (mirrors COBOL CHECK-ARGS) ---------- */
test("status -1: months out of range", () => {
  for (const fn of [compound, amort, saving]) {
    assert.equal(fn(0, 100, 100, 0).s, -1);
    assert.equal(fn(1201, 100, 100, 0).s, -1);
    assert.equal(fn(-3, 100, 100, 0).s, -1);
  }
});

test("status -2/-3: negative principal / negative rate", () => {
  for (const fn of [compound, amort, saving]) {
    assert.equal(fn(12, -1, 100, 0).s, -2);
    assert.equal(fn(12, 100, -1, 0).s, -3);
  }
});

test("status -4: amort payment cannot cover interest; saving negative deposit", () => {
  assert.equal(amort(12, 100000, 1200, 500).s, -4);
  assert.equal(amort(12, 100000, 1200, 0).s, -4);
  assert.equal(saving(12, 100, 100, -1).s, -4);
});

test("outputs are zeroed on error", () => {
  const out = amort(0, 500, 500, 500);
  assert.deepEqual(out, { a: 0, b: 0, c: 0, s: -1 });
});
